# Generated by Django 3.0.4 on 2022-10-29 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 10, 29, 14, 26, 6, 87324, tzinfo=utc), max_length=19),
        ),
    ]
